[kvm_vms]
proxmox-lab ansible_host=192.168.122.119 ansible_user=root

[kvm_vms:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
